language: ruby
cache: bundler
sudo: false
rvm: 2.4.3
install:
- bundle install
script:
- bundle exec rake build:prod
- bundle exec rake postbuild:test
addons:
  ssh_known_hosts: ssh-sudweb.alwaysdata.net
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
after_deploy:
- ssh-agent -k
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet --exclude '.ssh' $TRAVIS_BUILD_DIR/_site/2019/
    sudweb_2019@ssh-sudweb.alwaysdata.net:/home/sudweb/www/2019/
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - WEEZEVENT_EVENT_ID=218160
before_install:
- openssl aes-256-cbc -K $encrypted_913e2c12d44b_key -iv $encrypted_913e2c12d44b_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_913e2c12d44b_key -iv $encrypted_913e2c12d44b_iv
  -in deploy_rsa.enc -out deploy_rsa -d
